name: GitHub Actions Deploy
run-name: Github action deploy on push
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    name: id_rsa # optional
                    known_hosts: ${{ secrets.SSH_HOSTS }}
                    config: ${{ secrets.CONFIG }} # ssh_config; optional
                    if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
            - name: Pull
            run: ssh ubuntu@${{ secrets.SSH_HOSTS }} "cd Projects/handbookhub_server && git pull origin main"