name: GitHub Actions Deploy
run-name: Github action deploy on push
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  name: id_rsa # optional
                  known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
                  config: ${{ secrets.CONFIG }} # ssh_config; optional
                  if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
            - name: Connect
              env:
                HOST: ${{ secrets.SSH_HOST }}
              run: ssh ubuntu@"$HOST"
            - name: Pull
              run: cd ~/Projects/handbookhub_server && git pull origin main
            - name: Update submodules
              run: git submodule update --remote --recursive
            - name: Update packages
              run: source venv/bin/activate && pip install -r requirements.txt