name: GitHub Actions Deploy
run-name: Github action deploy on push
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Key
              shell: bash
              env:
                KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: echo "$KEY" > private.key && chmod 400 private.key && echo "$(cat private.key)"
            - name: Pull
              env:
                HOST: ${{ secrets.SSH_HOST }}
              run: ssh -i private.key ubuntu@"$HOST" "cd Projects/handbookhub_server && git pull origin main"